services:
  - type: web
    name: miller-lights
    env: node
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: miller-lights-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    staticPublishPath: ./client/build

  - type: postgres
    name: miller-lights-db
    ipAllowList: []
    plan: free 